### ISSUE TITLE
MarshalBinary fails for dictionary of size 1.7Mb

### ISSUE THREAD

**Issue by c-iyer** [hideo55/go-loudstrie#2]
This might not be a bug in the loudstrie code itself. 
I encountered the following stack trace when trying to dump the binary for of the loudtrie that was built from a dictionary of size 1.7Mb on disk.
The dictionary contains exactly 129015 terms. 

As you can see below this happens when trying to allocate a new slice, so I am not sure if the louds code is causing this but maybe you can workaround this error.

```
bad slice in frame github.com/hideo55/go-loudstrie.(*TrieData).MarshalBinary at 0xc2083b3da0: 0xc2081d8d67/0xc/0x0
fatal error: slice capacity smaller than length

runtime stack:
runtime.throw(0xaf656f)
    /usr/lib/golang/src/pkg/runtime/panic.c:520 +0x69 fp=0x7ffda9c187c8 sp=0x7ffda9c187b0
scanbitvector(0xa56538, 0x897901, 0xc2083b3db0, 0x7ffda9c18880, 0x429001, 0x7ffda9c18a90)
    /usr/lib/golang/src/pkg/runtime/mgc0.c:1538 +0x258 fp=0x7ffda9c18830 sp=0x7ffda9c187c8
scanframe(0x7ffda9c18900, 0x7ffda9c18a90)
    /usr/lib/golang/src/pkg/runtime/mgc0.c:1622 +0x2e1 fp=0x7ffda9c188a8 sp=0x7ffda9c18830
runtime.gentraceback(0x40a146, 0xc2083b37b0, 0x0, 0xc208002120, 0x0, 0x0, 0x7fffffff, 0x408880, 0x7ffda9c18a90, 0x27ff4776e5000)
    /usr/lib/golang/src/pkg/runtime/traceback_x86.c:253 +0x744 fp=0x7ffda9c18990 sp=0x7ffda9c188a8
addstackroots(0xc208002120, 0x7ffda9c18a90)
    /usr/lib/golang/src/pkg/runtime/mgc0.c:1692 +0x168 fp=0x7ffda9c18a20 sp=0x7ffda9c18990
markroot(0xc208018480, 0x5)
    /usr/lib/golang/src/pkg/runtime/mgc0.c:1321 +0xbe fp=0x7ffda9c18aa0 sp=0x7ffda9c18a20
runtime.parfordo(0xc208018480)
    /usr/lib/golang/src/pkg/runtime/parfor.c:88 +0xa3 fp=0x7ffda9c18b18 sp=0x7ffda9c18aa0
gc(0xc2083b37c8)
    /usr/lib/golang/src/pkg/runtime/mgc0.c:2407 +0x1d6 fp=0x7ffda9c18c48 sp=0x7ffda9c18b18
mgc(0xc208002120)
    /usr/lib/golang/src/pkg/runtime/mgc0.c:2349 +0x2e fp=0x7ffda9c18c58 sp=0x7ffda9c18c48
runtime.mcall(0x42a497)
    /usr/lib/golang/src/pkg/runtime/asm_amd64.s:181 +0x4b fp=0x7ffda9c18c68 sp=0x7ffda9c18c58

goroutine 16 [garbage collection]:
runtime.gc(0x7ff400000000)
    /usr/lib/golang/src/pkg/runtime/mgc0.c:2329 +0x1c6 fp=0xc2083b37e0 sp=0xc2083b37b0
runtime.mallocgc(0x10, 0x69c461, 0x1)
    /usr/lib/golang/src/pkg/runtime/malloc.goc:205 +0x1d6 fp=0xc2083b3848 sp=0xc2083b37e0
cnew(0x69c460, 0xc, 0x1)
    /usr/lib/golang/src/pkg/runtime/malloc.goc:836 +0xc1 fp=0xc2083b3868 sp=0xc2083b3848
runtime.cnewarray(0x69c460, 0xc)
    /usr/lib/golang/src/pkg/runtime/malloc.goc:849 +0x3a fp=0xc2083b3888 sp=0xc2083b3868
makeslice1(0x68c940, 0xc, 0xc, 0xc2083b38e8)
    /usr/lib/golang/src/pkg/runtime/slice.goc:55 +0x4d fp=0xc2083b38a0 sp=0xc2083b3888
runtime.makeslice(0x68c940, 0xc, 0xc, 0x0, 0xc, 0xc)
    /usr/lib/golang/src/pkg/runtime/slice.goc:36 +0xb3 fp=0xc2083b38d0 sp=0xc2083b38a0
encoding/binary.Write(0x7ff475bef080, 0xc2080288c0, 0x7ff4787a2128, 0x0, 0x68c940, 0xc2097280e0, 0x0, 0x0)
    /usr/lib/golang/src/pkg/encoding/binary/binary.go:236 +0xd7 fp=0xc2083b3c70 sp=0xc2083b38d0
github.com/hideo55/go-loudstrie.(*TrieData).MarshalBinary(0xc20803e000, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/go/src/github.com/hideo55/go-loudstrie/loudstrie.go:436 +0x151a fp=0xc2083b3dc0 sp=0xc2083b3c70
```

**Comment by hideo55** [comment]
I tried to make dictionary of size over 100MB. But, couldn't reproduce this problem.

I tested on:

```
$ go version                                                                                                                                                         
go version go1.4.2 darwin/amd64
```

.

**Comment by c-iyer** [comment]
Yes it looks like this issue in addressed in go1.4.2
The version I was running with was go1.3.3
